### ISSUE TITLE
Diseñar el aspecto visual de la pagina principal con Html

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#10]
Tiempo: 4 horas
Fecha limite:  10 Marzo 2016
Descripción: Con el uso de el lenguaje Html, se creara  la pagina principal, con el objetivo de mostrar el logo, ademas de dos botones, los cuales serán,  crear proyecto y ver proyectos.

**Comment by Cristinacespedes** [comment]
Muchachos les envió el código mediante correo electrónico

**Comment by Cristinacespedes** [comment]
https://github.com/UnisoftCorporated/Unisoft/commit/afe9445d6eed7aced4e132dee9877f6ae6c4518a  Muchachos el codigo en el commit.
