### ISSUE TITLE
Crear  base de datos.

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#11]
Tiempo: 8 horas
Fecha limite: 11 Marzo 2016
Descripción: Se creara una base de datos utilizando las herramientas de Google Cloud SQL, y el leguaje python, con el fin de almacenar el nombre de los proyectos que se creen, con su respectivo administrador y el nombre de los miembros del equipo

**Comment by pollowf8** [comment]
Buenos días, la hubieron inconvenientes al crear la base de datos en google cloud sql, ya que solo ofrecen un servicios con un periodo de prueba con funciones limitadas, se opta por alojar la base de datos en un webhosting para acceder a la base de datos desde cualquier sitio.

**Comment by pollowf8** [comment]
buenas noches, en vista de que muchos webhosting no permiten conexiones remotas a las bases de datos, se toma como solución definitiva a amazon web services, el cual nos provee un servicio de base de datos en la nube, y estamos trabajando con postgresql.  

Agrego imágenes de la base de datos en la nube 
![captura de pantalla de 2016-03-11 21 47 24](https://cloud.githubusercontent.com/assets/15186379/13720632/157f9f20-e7dc-11e5-9459-5979e443287e.png)
![Uploading Captura de pantalla de 2016-03-11 21:48:04.png…]()
