### ISSUE TITLE
Diseñar el aspecto visual de la pagina principal con Css

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#14]
Con el uso de el lenguaje css, se iniciara el diseño del aspecto visual de la pagina principal, con el objetivo de mostrar el logo, ademas de dos botones, los cuales serán, crear proyecto y ver proyectos (sin ninguna función por ahora).

**Comment by Cristinacespedes** [comment]
Muchachos codigo preliminar del issue 
https://github.com/UnisoftCorporated/Unisoft/commit/28a4d7759e5f81701fbbc8e0e89f667561ecc54d
