### ISSUE TITLE
Crear conexión de la base de datos con python

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#15]
Tiempo: 8 horas
Fecha limite: 11 Marzo 2016
Descripción:Con el uso de el  lenguaje python, se realizara la conexión necesaria con la base de datos en la nube, para después enviar los  datos suministrados por el usuario en la pagina html a la hora de crear el proyecto.

**Comment by pollowf8** [comment]
la conexción de python con la base de datos, en el archivo va la informacion para la conexcion la base de dato en la nube.

https://github.com/UnisoftCorporated/Unisoft/blob/master/postgres.py
