### ISSUE TITLE
Crear formulario para agregar integrantes  con Html5.

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#20]
Tiempo: 4 horas
Fecha Limite: 1 abril
Descripción: Se realizara la creación del formulario que permitirá guardar los datos personales de los integrantes del grupo los cuales serán guardados  en la base de datos, este formulario se creara usando el lenguaje HTML5.

**Comment by Cristinacespedes** [comment]
solucion https://github.com/UnisoftCorporated/Unisoft/blob/master/Formulario%20Integrantes/integrantes.html
