### ISSUE TITLE
Crear formulario para agregar integrantes  con Css.

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#21]
Tiempo: 8 horas
Fecha Limite: 1 abril
Descripción: Se realizara la creación del formulario que permitirá guardar los datos personales de los integrantes del grupo los cuales serán guardados en la base de datos, este formulario se creara usando el lenguaje css.

**Comment by Cristinacespedes** [comment]
Solución https://github.com/UnisoftCorporated/Unisoft/blob/master/Formulario%20Integrantes/INTEGRANTES.CSS
