### ISSUE TITLE
Extraer cantidad de mensajes recibidos en Gmail de un respectivo usuario.

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#22]
Se implementara el software para poder extraer la cantidad de mensajes recibidos en gmail.

**Comment by facanor** [comment]
El software es capaz de extraer la cantidad de mensajes recibidos. Se implementan otros métodos, el que es capaz de extraer la cantidad de mensajes enviados y el de las fechas, sin embargo, no se ponen en marcha porque se están probando permisos y credenciales de los miembros del equipo.
