### ISSUE TITLE
Especificar el estandar de codificacion

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#23]
Tiempo: 8 horas
Fecha limite: 11 abril 2016
Descripción:Especificar el estándar que sera usado por los miembros de Unisoft Corporated para el desarrollo de todos los códigos introducidos en el repositorio.

**Comment by Cristinacespedes** [comment]
El estandar de codificacion quedara guardado en la wiki en la siguiente direccion https://github.com/UnisoftCorporated/Unisoft/wiki/Est%C3%A1ndar-de-codificacion
