### ISSUE TITLE
Diseñar una tabla en  la base de datos para que guarde la información del master

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#25]
Tiempo: 8 horas
Fecha limite: 1 abril 2016
Descripción: En la base de datos Amazon Services, se creara la respectiva tabla para guardar la información del master.

**Comment by pollowf8** [comment]
tabla para el master creada, incluye su variable para subir la imagen del master
[segundosql.txt](https://github.com/UnisoftCorporated/Unisoft/files/199645/segundosql.txt)
