### ISSUE TITLE
Listar la cantidad de mensajes enviados de una persona

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#29]
Tiempo: 8 horas.
Fecha limite: 15 Abril 2016.
Descripción: Listar la cantidad de mensajes enviados de una sola persona y mostrar información.

**Comment by Cristinacespedes** [comment]
Tarea solucionada, el código se puede ver aqui 45b3ed43ac43c01dd1cc2fdadd3faede2bd374fc
