### ISSUE TITLE
Crear Historias de Usuario del proyecto 

### ISSUE THREAD

**Issue by facanor** [UnisoftCorporated/Unisoft#3]
Tiempo: 4 horas
Fecha limite: 24 Febrero 2016
Descripción: Crear historias de usuario del aplicativo, el cual se desarrolla con el fin de mostrar un mejor diseño e implementar la funcionalidad de visualizar las estadísticas interactivas que presenta un grupo de desarrollo, utilizando como medio de referencia la comunicación realizada mediante correos de GMAIL.

**Comment by alom5934** [comment]
Debido a dificultades personales, subiré las historias de usuario el día de mañana 25 de febrero 2016

**Comment by alom5934** [comment]
Las historias de Usuario creadas, quedan registradas en la Wiki.

**Comment by alom5934** [comment]
Las historias de Usuario, ya fueron modificadas, quedan registradas en la wiki.
Historia de usuario 1: https://github.com/UnisoftCorporated/Unisoft/wiki/Historia-de-Usuario-%231
Historia de usuario 1.1: https://github.com/UnisoftCorporated/Unisoft/wiki/Historia-de-Usuario-%232
