### ISSUE TITLE
Listar la cantidad de mensajes recibidos de una persona.

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#30]
Tiempo: 8 horas.
Fecha limite: 15 Abril 2016.
Descripción: Listar la cantidad de mensajes recibidos de una sola persona y mostrar la información.

**Comment by Cristinacespedes** [comment]
Tarea solucionada, el código se puede ver aqui 03a77828ce032bce9184b2b627569e713a27f8f6
