### ISSUE TITLE
Obtener la id de los mensajes enviados usando filtros

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#38]
Tiempo: 8 horas.
Fecha limite: 13 Abril 2016.
Descripción: Usar diferentes filtros para obtener la id de los mensajes.

**Comment by facanor** [comment]
Filtré la Id de los correos tomando como ejemplo el correo "fabianwf8@gmail.com", y muestro la id extraída de la solicitud.
