### ISSUE TITLE
Crear el Botón principal el cual dará acceso a nuestra aplicación 

### ISSUE THREAD

**Issue by facanor** [UnisoftCorporated/Unisoft#4]
Tiempo: 8 horas
Fecha Limite: 23 de Febrero
Descripción: Crear el botón principal con el cual se podrá acceder de forma directa a nuestra aplicación

**Comment by pollowf8** [comment]
Para la creación del botón de la aplicación embebida en gmail  se deben adquirir servicios de dominio para cuentas empresariales con google app for work y google app, las cuales tienen un costo muy elevado para el desarrollo del proyecto, por tanto se opta desarrollar una exención para google chrome y desde  allí realizar el desarrollo y enlace relacionado posteriormente con el proyecto.
