### ISSUE TITLE
Backlog sprint Review 4

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#45]
Tiempo: 4 horas
Fecha limite: 22 abril 2016
Descripción:Realizar la Lista de tareas que se asignaron para el cuarto Sprint con el fin de completar los objetivos. Esta lista permite ver  el avance de cada una de las tareas.

**Comment by cristianalba** [comment]
![sprint backlog 4 1](https://cloud.githubusercontent.com/assets/17344019/15526405/6c4aae4e-21f7-11e6-8831-264591b2a4c7.png)

**Comment by cristianalba** [comment]
![sprint backlog 4 2](https://cloud.githubusercontent.com/assets/17344019/15526410/7224354c-21f7-11e6-9065-3668b4d16004.png)
