### ISSUE TITLE
Documentar el repositorio

### ISSUE THREAD

**Issue by facanor** [UnisoftCorporated/Unisoft#46]
Duración: 4 horas.
Fecha Limite: 12 de Abril
Descripción: Mediante archivos en formato markdown especificar las partes del repositorio para mejorar la organización en aportes futuros.

**Comment by cristianalba** [comment]
Acá pueden observar el README general del proyecto : https://github.com/UnisoftCorporated/Unisoft

README de la versión 1.0 

Examples : https://github.com/UnisoftCorporated/Unisoft/tree/master/Version_1.0/Examples

Interface: https://github.com/UnisoftCorporated/Unisoft/tree/master/Version_1.0/Interface

Sources:https://github.com/UnisoftCorporated/Unisoft/tree/master/Version_1.0/Sources
