### ISSUE TITLE
Backlog sprint review 5

### ISSUE THREAD

**Issue by Cristinacespedes** [UnisoftCorporated/Unisoft#50]
Tiempo: 4 horas
Fecha limite: 6 mayo 2016
Descripción:Realizar la Lista de tareas que se asignaron para el cuarto Sprint con el fin de completar los objetivos. Esta lista permite ver el avance de cada una de las tareas.

**Comment by cristianalba** [comment]
![sprint backlog 5](https://cloud.githubusercontent.com/assets/17344019/15526414/7c39199e-21f7-11e6-8efe-1345e7a9112e.png)
