### ISSUE TITLE
Documentación Sprint Review 5

### ISSUE THREAD

**Issue by Cristinacespedes** [UnisoftCorporated/Unisoft#51]
Tiempo: 4 horas.
Fecha limite: 6 mayo 2016.
Descripción: Se realizara la respectiva documentación, de la cuarta entrega, la cual tendrá la información de cada una de las tareas con sus respectivos problemas y soluciones.

**Comment by alom5934** [comment]
la documentacion se encuentra en el siguiente link : https://github.com/UnisoftCorporated/Unisoft/wiki/Documentaci%C3%B3n-Sprint-5.
