### ISSUE TITLE
Ajustar pagina Html para mostrar información del proyecto.

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#52]
Tiempo: 8 horas
Fecha limite: 6 mayo 2016
Descripción: Utilizar una plantilla, y ajustarla para que se pueda observar la información general del proyecto, la cual queda como pagina principal.

**Comment by Cristinacespedes** [comment]
El código correspondiente a esta tarea esta aquí https://github.com/UnisoftCorporated/Unisoft/commit/556ccec8023fbca96dcd12a3f8c4253d0632146c
