### ISSUE TITLE
Generar documento de texto que contenga información relacionada a la pagina principal.

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#53]
Tiempo: 4 horas
Fecha limite: 6 mayo 2016
Descripción: Generar un documento de texto, en el cual se va a realizar una descripción general del uso de la aplicación.

**Comment by Cristinacespedes** [comment]
El documento que contiene la información mostrada en la pagina principal esta https://github.com/UnisoftCorporated/Unisoft/commit/2c3d1ba6c3ac1b9c78fc6dd9d5ff3aa98406f37b.
