### ISSUE TITLE
Implementar el botón en las Aplicaciónes de Gmail

### ISSUE THREAD

**Issue by facanor** [UnisoftCorporated/Unisoft#6]
Tiempo: 8 horas
Fecha Limite: 25 Febrero
Descripción: Añadir el botón creado a la lista de aplicaciones de Gmail, teniendo por objetivo un fácil y rápido acceso a nuestros servicios conformados por diseño agradable en el momento de crear o editar un grupo,una eficiente información estadística de interacción entre el grupo.

**Comment by Cristinacespedes** [comment]
debido al inconveniente por los costos que representa la creación del botón de la aplicación, ya mencionados con anterioridad por otro miembro del equipo se opta por la alternativa de crear una extensión, realizando así dicha extensión y creando un despliegue principal, encontrando dificultades para realizar un enlace de direccionamiento que sera solucionado posteriormente.

**Comment by Cristinacespedes** [comment]
El código donde se crea la extensión con el respectivo despliegue principal quedara en el repositorio. https://github.com/UnisoftCorporated/Unisoft.git
