### ISSUE TITLE
Ajustar pagina html de bandeja de entrada.

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#60]
Tiempo: 8 horas
Fecha limite: 6 mayo 2016
Descripción: Utilizar una plantilla, y ajustar bandeja de entrada que permita visualizar la información extraída como por ejemplo los mensajes enviados y recibidos.

**Comment by pollowf8** [comment]
Plantilla modificada y ajustada para la bandeja de mensajes.
