### ISSUE TITLE
Filtrar mensajes, por etiquetas propias de Gmail.

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#62]
Tiempo: 8 horas
Fecha limite: 26 mayo 2016
Descripción: Realizar las funciones para que los mensajes de Gmail, se filtren por las etiquetas creadas por Unisoft

**Comment by facanor** [comment]
Se filtra por las etiquetas:
[Importante]
[Ayuda]
[Error]
[Pregunta]
[Tarea]
[Invalido]
[Duplicado]
[Solución]
