### ISSUE TITLE
Filtrar mensajes, por etiquetas de Unisoft.

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#63]
Tiempo: 8 horas
Fecha limite: 27 mayo 2016
Descripción: filtrar los mensajes del grupo de trabajo, extrayendo la cantidad de mensajes sean enviados o recibidos.

**Comment by Cristinacespedes** [comment]
El codigo adecuado para realizar el filtro queda en el repositorio. https://github.com/UnisoftCorporated/Unisoft/commit/723e41447bc2a9112e2b2d94702a832c9877f5d2
