### ISSUE TITLE
Crear manual de sistema (documentacion).

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#68]
Tiempo: 8 horas
Fecha limite: 27 mayo 2016
Descripción:Realizar la documentación del sistema, en el cual se explica, las acciones que se pueden realizar en el software de Unisoft

**Comment by facanor** [comment]
El manual del sistema estará sujeto a futuras modificaciones, será entregado junto con la aplicación en un formato word.
