### ISSUE TITLE
Agregar un  dominio y hosting para la pagina web de Unisoft.

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#69]
Tiempo: 8 horas
Fecha limite: 27 mayo 2016
Descripción:Agregar un dominio para la pagina web de Unisoft.

**Comment by pollowf8** [comment]
El dominio y hosting los provee http://5jelly.info no s ofrece un servcio de almacenamiento de de 10GB, el dominio es unisoftcorp.yohosts.info.
