### ISSUE TITLE
realizar Backlog Primer Sprint y su respectiva documentación.

### ISSUE THREAD

**Issue by facanor** [UnisoftCorporated/Unisoft#7]
Tiempo: 4 horas
Fecha Limite: 25 de Febrero del 2016
Descripción: Generar la documentación referente al primer sprint del proyecto, juntando los casos de usos, explicando las herramientas utilizadas y el manejo de la aplicación.

**Comment by cristianalba** [comment]
Buenos dias, este es el Backlog del primer Sprint.
![backlog](https://cloud.githubusercontent.com/assets/17344019/13373587/8d768794-dd39-11e5-9248-84b0ad8e26a2.png)

**Comment by cristianalba** [comment]
`closes / fixes #NN`

**Comment by cristianalba** [comment]
https://github.com/UnisoftCorporated/Unisoft.wiki.git

Compañeros acá pueden revisar la documentación del SPRINT 1
