### ISSUE TITLE
Agregar a la aplicacion, la accesibilidad, para las personas con discapacidades visuales.

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#71]
Tiempo: 8 horas
Fecha limite: 27 mayo 2016
Descripción:Agregar a la aplicación, la accesibilidad, para las personas con discapacidades visuales.

**Comment by cristianalba** [comment]
Para dar la accesibilidad a personas con discapacidad visual, se utilizó la extensión Chromevox, una herramienta  que integra un lector de pantallas en el propio navegador
