### ISSUE TITLE
Modificar codigo actual, para que las funciones retornen sus respectivos valores.

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#72]
Tiempo: 8 horas
Fecha limite: 27 mayo 2016
Descripción:Lograr adaptar y modificar el código actual para lograr que los valores sean retornados, para poder realizar el manejo de la información.

**Comment by Cristinacespedes** [comment]
https://github.com/UnisoftCorporated/Unisoft/blob/master/Version_2.0/Sources/Scripts/Funcion_retorno.js
