### ISSUE TITLE
Backlog sprint review 6

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#73]
Tiempo: 4 horas
Fecha limite: 26 mayo 2016
Descripción:Realizar la Lista de tareas que se asignaron para el sexto Sprint con el fin de completar los objetivos. Esta lista permite ver el avance de cada una de las tareas.

**Comment by cristianalba** [comment]
![sprint 6 1](https://cloud.githubusercontent.com/assets/17344019/15623508/1230b9e0-243a-11e6-98d7-9a06980bd4fe.png)

**Comment by cristianalba** [comment]
![sprint 6 2](https://cloud.githubusercontent.com/assets/17344019/15623510/1a95bc7a-243a-11e6-973f-b9abd7e3ee65.png)
