### ISSUE TITLE
Creación historia de usuario #6

### ISSUE THREAD

**Issue by alom5934** [UnisoftCorporated/Unisoft#75]
Tiempo: 4 horas
Fecha limite: 26 mayo 2016
Descripción: Representación especifica del objetivo presentado para el sprint, de la cual se derivan las tareas a realizar.

**Comment by Cristinacespedes** [comment]
la respectiva historia de usuario se puede encontrar aquí  https://github.com/UnisoftCorporated/Unisoft/wiki/Historia-de-usuario-%236
