### ISSUE TITLE
Crear Backlog

### ISSUE THREAD

**Issue by facanor** [UnisoftCorporated/Unisoft#9]
Tiempo: 4 horas
Fecha limite: 11 Marzo 2016
Descripción:Realizar la Lista de tareas que se asignaron para el segundo Sprint con el fin  de completar los objetivos.
Esta lista  se permite ver las tareas en las que se está teniendo problemas, con lo que le permite tomar decisiones al respecto.

**Comment by cristianalba** [comment]
![backlog2](https://cloud.githubusercontent.com/assets/17344019/13720634/15f8bf18-e7dc-11e5-8dda-aefcdf301d21.png)

**Comment by cristianalba** [comment]
Backlog Sprint 2
![backlog2](https://cloud.githubusercontent.com/assets/17344019/13720705/90039c46-e7dd-11e5-9877-9d1a13a8bd81.png)
